version: "3.3"

services:
  server:
    build:
      context: ./
    restart: unless-stopped
    command: ./server
    environment:
      PORT: 8181
    ports:
      - "8181:8181"
    volumes:
      - data:/go/monitect/data
      - ./conf/:/go/monitect/conf/
  dht22-1:
    build:
      context: ./sensors
    restart: unless-stopped
    command: dht22.py -i 300
    # need to run privileged for access to gpio
    privileged: true
    environment:
      SERVER_URL: "http://server:8181"
    volumes:
      - ./sensors/dht22.py:/dht22.py

volumes:
  data: {}
