version: "3.3"

services:
  server:
    build:
      context: ./
    restart: on-failure
    command: ./server
    environment:
      PORT: 8181
    ports:
      - "8181:8181"
    volumes:
      - data:/go/monitect/data
      - ./conf/:/go/monitect/conf/

volumes:
  data: {}
