version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api.Dockerfile
    # restart: unless-stopped
    command: "./configs/server.yaml"
    volumes:
      - data:/data
      - ./configs/:/configs/
  web:
    build:
      context: ./
      dockerfile: ./docker/web.Dockerfile
    depends_on:
      - api
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: unless-stopped
  # dht22-1:
  #   build:
  #     context: ./sensors
  #   restart: unless-stopped
  #   command: dht22.py -i 300
  #   # need to run privileged for access to gpio
  #   privileged: true
  #   environment:
  #     SERVER_URL: "http://server:8181"
  #   volumes:
  #     - ./sensors/dht22.py:/dht22.py

volumes:
  data: {}
