version: "3.3"

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api.Dockerfile
    # restart: unless-stopped
    command: "./configs/server.yaml"
    volumes:
      - data:/data
      - ./configs/:/configs/
  web:
    build:
      context: ./
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  data: {}
